#!/bin/bash

IP=$1
INT=$2
DEFAULT=/etc/default/ec2watcher
AWS_PROFILE=/etc/aws_profile.conf

LOG_FILE=/var/log/ec2watcher-$IP.log

if [ -f $AWS_PROFILE ]
then
    . $AWS_PROFILE
fi

if [ -f "$DEFAULT" ]
then
    . "$DEFAULT"
fi

if [ ! -f $LOG_FILE ]
then
    touch $LOG_FILE
fi

if [ -z $AWS_ACCESS_KEY ]
then
    echo `date +%Y%m%d-%H%M%S` "[$0 $@]: Please cheack your $AWS_PROFILE configuration file. You have a problem with the AWS_ACCESS_KEY variable" 2>&1 | tee -a $LOG_FILE
    exit 1;
elif [ -z $AWS_SECRET_KEY ]
then
    echo `date +%Y%m%d-%H%M%S` "[$0 $@]: Please cheack your $AWS_PROFILE configuration file. You have a problem with the AWS_SECRET_KEY variable" 2>&1 | tee -a $LOG_FILE
    exit 1;
elif [ -z $EC2_BIN ]
then
    echo `date +%Y%m%d-%H%M%S` "[$0 $@]: Please cheack your $AWS_PROFILE configuration file. You have a problem with the EC2_BIN variable" 2>&1 | tee -a $LOG_FILE
    exit 1;
fi

if [ ! -f $EC2_BIN/ec2-describe-instances ]
then
    echo `date +%Y%m%d-%H%M%S` "[$0 $@]: $EC2_BIN/ec2-describe-instances doesn't exist. Please check your ec2 home in $AWS_PROFILE" 2>&1 | tee -a $LOG_FILE
    exit 1;
fi

echo -e `date +%Y%m%d-%H%M%S` "\n [$0 $@]: Starting daemon...\n" 2>&1 | tee -a $LOG_FILE

while :
do
    $EC2W_HOME/ec2checker $IP 2

    sleep $INT
done
